name: CD on tag release

on:
    push:
      tags:
        - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create ZIP source code archive
        run: |
          zip -r ../sourceCode.zip . -x "node_modules/*" -x "build"

      - name: Create TAR.GZ source code archive
        run: |
          tar -czvf ../sourceCode.tar.gz --exclude="node_modules" --exclude="build" -C . .

      - name: Create ZIP build archive
        run: |
          zip -r ../build.zip ./build

      - name: Create TAR.GZ build archive
        run: |
          tar -czvf ../build.tar.gz -C ./build .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Changes in this Release
          draft: true
          prerelease: false

      - name: Upload ZIP Source Code artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../sourceCode.zip
          asset_name: sourceCode.zip
          asset_content_type: application/zip

      - name: Upload TAR.GZ Source Code artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../sourceCode.tar.gz
          asset_name: sourceCode.tar.gz
          asset_content_type: application/x-gtar

      - name: Upload ZIP build artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../build.zip
          asset_name: build.zip
          asset_content_type: application/zip

      - name: Upload TAR.GZ build artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../build.tar.gz
          asset_name: build.tar.gz
          asset_content_type: application/x-gtar
    
      - name: Successfully create release
        run: | 
          echo "Release created successfully"
          echo "Please now write the release documentation"
          
      - name: Setup ssh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > identity
          chmod 400 identity
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
  
      - name: Deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH_PROD }}
        run: |
          scp -i identity -r ./build/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH